### ISSUE TITLE
Load generator has extreme high failure rates even without treatments

### ISSUE THREAD

**Issue by JulianLegler** [JulianLegler/oxn#1]
When the load generator is running, the amount of 503 error responses is extreme high (>99%).

Jaeger is reporting it as:
error.reason: remote connection failure

The request is not even passing through the frontendproxy service.

Example from a report:
```yaml
loadgen:
  loadgen_start_time: 2024-08-02 12:26:37.593373
  loadgen_end_time: 2024-08-02 12:36:37.724289
  loadgen_total_requests: 1282167
  loadgen_total_failures: 1276042
  task_details:
    9c5dfa704ccb477a:
      url: /api/products/0PUK6V6EV0
      verb: GET
      requests: 582911
      failures: 580404
      fail_ratio: 0.995699171914752
      sum_response_time: 6741007
      min_response_time: 0
      max_response_time: 428
      avg_response_time: 11.56438461446087
      median_response_time: 11
    966fc02f7fac48bc:
      url: /api/cart
      verb: GET
      requests: 174586
      failures: 173674
      fail_ratio: 0.9947762134420859
      sum_response_time: 2028072
      min_response_time: 0
      max_response_time: 433
      avg_response_time: 11.616464092195251
      median_response_time: 11
    11c36c0777014417:
      url: /api/data
      verb: GET
      requests: 175659
      failures: 174672
      fail_ratio: 0.9943811589500111
      sum_response_time: 2051430
      min_response_time: 0
      max_response_time: 439
      avg_response_time: 11.678479326422217
      median_response_time: 11
    281090c632cc4f8c:
      url: /api/cart
      verb: POST
      requests: 116453
      failures: 115794
      fail_ratio: 0.9943410646355182
      sum_response_time: 1376096
      min_response_time: 0
      max_response_time: 473
      avg_response_time: 11.816750105192654
      median_response_time: 11
    59405a35e59a4239:
      url: /api/recommendations
      verb: GET
      requests: 174709
      failures: 173945
      fail_ratio: 0.9956270140633854
      sum_response_time: 2107700.369749844
      min_response_time: 0
      max_response_time: 1282.6131414622068
      avg_response_time: 12.064062926064736
      median_response_time: 11
    73af282c93b14f66:
      url: /
      verb: GET
      requests: 57849
      failures: 57553
      fail_ratio: 0.9948832304793515
      sum_response_time: 687995.8525640368
      min_response_time: 0
      max_response_time: 1101.1365931481123
      avg_response_time: 11.892960164636154
      median_response_time: 11
            ```

**Comment by JulianLegler** [comment]
The first few thousand requests seem to be returning 200s and are fine. At some point in time everything seems to be blocked or the locust implementation can't keep up.

**Comment by JulianLegler** [comment]
Seems like there is no limitation for the requests, so there is probably some congestion problem.

Limiting the requests to 50 per locust task is lowering the errors tremendous. 

```yaml
loadgen:
  loadgen_start_time: 2024-08-02 15:21:59.386575
  loadgen_end_time: 2024-08-02 15:31:59.494648
  loadgen_total_requests: 13470
  loadgen_total_failures: 1983
  task_details:
    99a89be275044039:
      url: /api/recommendations
      verb: GET
      requests: 1866
      failures: 759
      fail_ratio: 0.4067524115755627
      sum_response_time: 32360
      min_response_time: 4
      max_response_time: 76
      avg_response_time: 17.341907824222936
      median_response_time: 19
    7208fa279c62477d:
      url: /api/cart
      verb: GET
      requests: 1806
      failures: 0
      fail_ratio: 0.0
      sum_response_time: 11444
      min_response_time: 1
      max_response_time: 22
      avg_response_time: 6.336655592469546
      median_response_time: 7
    38a8474c67774e82:
      url: /api/products/0PUK6V6EV0
      verb: GET
      requests: 6144
      failures: 1224
      fail_ratio: 0.19921875
      sum_response_time: 33747
      min_response_time: 1
      max_response_time: 36
      avg_response_time: 5.49267578125
      median_response_time: 6
    06ef6026449c418d:
      url: /api/cart
      verb: POST
      requests: 1168
      failures: 0
      fail_ratio: 0.0
      sum_response_time: 11141
      min_response_time: 2
      max_response_time: 57
      avg_response_time: 9.538527397260275
      median_response_time: 10
    f4236190fcdd4938:
      url: /
      verb: GET
      requests: 633
      failures: 0
      fail_ratio: 0.0
      sum_response_time: 8923
      min_response_time: 3
      max_response_time: 34
      avg_response_time: 14.096366508688783
      median_response_time: 16
    e7bdb42557844980:
      url: /api/data
      verb: GET
      requests: 1853
      failures: 0
      fail_ratio: 0.0
      sum_response_time: 18418
      min_response_time: 2
      max_response_time: 113
      avg_response_time: 9.939557474365893
      median_response_time: 11
```
